/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
type ManagerType string

// List of ManagerType
const (
	MANAGEMENT_CONTROLLER ManagerType = "ManagementController"
	ENCLOSURE_MANAGER ManagerType = "EnclosureManager"
	BMC ManagerType = "BMC"
	RACK_MANAGER ManagerType = "RackManager"
	AUXILIARY_CONTROLLER ManagerType = "AuxiliaryController"
	SERVICE ManagerType = "Service"
)