/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type MemorySummary struct {
	TotalSystemMemoryGiB float32 `json:"TotalSystemMemoryGiB,omitempty"`
	TotalSystemPersistentMemoryGiB float32 `json:"TotalSystemPersistentMemoryGiB,omitempty"`
	Status Status `json:"Status,omitempty"`
}
