/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
type BootSource string

// List of BootSource
const (
	NONE BootSource = "None"
	PXE BootSource = "Pxe"
	FLOPPY BootSource = "Floppy"
	CD BootSource = "Cd"
	USB BootSource = "Usb"
	HDD BootSource = "Hdd"
	BIOS_SETUP BootSource = "BiosSetup"
	UTILITIES BootSource = "Utilities"
	DIAGS BootSource = "Diags"
	UEFI_SHELL BootSource = "UefiShell"
	UEFI_TARGET BootSource = "UefiTarget"
	SD_CARD BootSource = "SDCard"
	UEFI_HTTP BootSource = "UefiHttp"
	REMOTE_DRIVE BootSource = "RemoteDrive"
	UEFI_BOOT_NEXT BootSource = "UefiBootNext"
)