/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
type IndicatorLed string

// List of IndicatorLED
const (
	UNKNOWN IndicatorLed = "Unknown"
	LIT IndicatorLed = "Lit"
	BLINKING IndicatorLed = "Blinking"
	OFF IndicatorLed = "Off"
)