/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ManagerType the model 'ManagerType'
type ManagerType string

// List of ManagerType
const (
	MANAGERTYPE_MANAGEMENT_CONTROLLER ManagerType = "ManagementController"
	MANAGERTYPE_ENCLOSURE_MANAGER ManagerType = "EnclosureManager"
	MANAGERTYPE_BMC ManagerType = "BMC"
	MANAGERTYPE_RACK_MANAGER ManagerType = "RackManager"
	MANAGERTYPE_AUXILIARY_CONTROLLER ManagerType = "AuxiliaryController"
	MANAGERTYPE_SERVICE ManagerType = "Service"
)
