/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
import (
	"os"
)
// InlineObject struct for InlineObject
type InlineObject struct {
	SoftwareImage *os.File `json:"softwareImage,omitempty"`
}
