/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// A Collection of ComputerSystem resource instances.
type Collection struct {
	// context
	OdataContext string `json:"@odata.context,omitempty"`
	// etag
	OdataEtag string `json:"@odata.etag,omitempty"`
	// id
	OdataId string `json:"@odata.id"`
	// type
	OdataType string `json:"@odata.type"`
	// description
	Description string `json:"Description,omitempty"`
	// Contains the members of this collection.
	Members []IdRef `json:"Members"`
	// The number of items in a collection.
	MembersodataCount int32 `json:"Members@odata.count,omitempty"`
	// The URI to the resource containing the next set of partial members.
	MembersodataNextLink string `json:"Members@odata.nextLink,omitempty"`
	// The name of the resource.
	Name string `json:"Name"`
}
