/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
type State string

// List of State
const (
	STATE_ENABLED State = "Enabled"
	STATE_DISABLED State = "Disabled"
	STATE_STANDBY_OFFLINE State = "StandbyOffline"
	STATE_STANDBY_SPARE State = "StandbySpare"
	STATE_IN_TEST State = "InTest"
	STATE_STARTING State = "Starting"
	STATE_ABSENT State = "Absent"
	STATE_UNAVAILABLE_OFFLINE State = "UnavailableOffline"
	STATE_DEFERRING State = "Deferring"
	STATE_QUIESCED State = "Quiesced"
	STATE_UPDATING State = "Updating"
)