/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ManagerLinks struct for ManagerLinks
type ManagerLinks struct {
	ManagerForServers []IdRef `json:"ManagerForServers,omitempty"`
	ManagerForChassis []IdRef `json:"ManagerForChassis,omitempty"`
	ManagerForSwitches []IdRef `json:"ManagerForSwitches,omitempty"`
	ManagerInChassis []IdRef `json:"ManagerInChassis,omitempty"`
}
