/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
type TransferMethod string

// List of TransferMethod
const (
	TRANSFERMETHOD_STREAM TransferMethod = "Stream"
	TRANSFERMETHOD_UPLOAD TransferMethod = "Upload"
)