/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type RedfishErrorError struct {
	MessageExtendedInfo []Message `json:"@Message.ExtendedInfo,omitempty"`
	Code string `json:"code"`
	Message string `json:"message"`
}
