/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// Message struct for Message
type Message struct {
	Message string `json:"Message,omitempty"`
	MessageArgs []string `json:"MessageArgs,omitempty"`
	MessageId string `json:"MessageId"`
	RelatedProperties []string `json:"RelatedProperties,omitempty"`
	Resolution string `json:"Resolution,omitempty"`
	Severity string `json:"Severity,omitempty"`
}
