/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type Status struct {
	Health Health `json:"Health,omitempty"`
	HealthRollup Health `json:"HealthRollup,omitempty"`
	State State `json:"State,omitempty"`
}
