/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// UpdateServiceActions struct for UpdateServiceActions
type UpdateServiceActions struct {
	UpdateServiceSimpleUpdate VirtualMediaActionsVirtualMediaEjectMedia `json:"#UpdateService.SimpleUpdate,omitempty"`
	UpdateServiceStartUpdate VirtualMediaActionsVirtualMediaEjectMedia `json:"#UpdateService.StartUpdate,omitempty"`
}
