/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// UpdateService Redfish Update Service.
type UpdateService struct {
	FirmwareInventory FirmwareInventory `json:"FirmwareInventory,omitempty"`
	// The name of the resource.
	Id string `json:"Id,omitempty"`
	// The name of the resource.
	Name string `json:"Name"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// description
	Description *string `json:"Description,omitempty"`
	HttpPushUri string `json:"HttpPushUri,omitempty"`
	ServiceEnabled *bool `json:"ServiceEnabled,omitempty"`
	Actions UpdateServiceActions `json:"Actions,omitempty"`
}
