/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// Manager Redfish manager resource.
type Manager struct {
	// The name of the resource.
	Id string `json:"Id,omitempty"`
	// The name of the resource.
	Name string `json:"Name"`
	UUID string `json:"UUID,omitempty"`
	ServiceEntryPointUUID string `json:"ServiceEntryPointUUID,omitempty"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// redfish copyright
	RedfishCopyright string `json:"@Redfish.Copyright,omitempty"`
	Model *string `json:"Model,omitempty"`
	ManagerType ManagerType `json:"ManagerType,omitempty"`
	Status Status `json:"Status,omitempty"`
	DateTime *string `json:"DateTime,omitempty"`
	// The time offset from UTC that the DateTime property is set to in format: +06:00 .
	DateTimeLocalOffset *string `json:"DateTimeLocalOffset,omitempty"`
	// description
	Description *string `json:"Description,omitempty"`
	EthernetInterfaces IdRef `json:"EthernetInterfaces,omitempty"`
	FirmwareVersion *string `json:"FirmwareVersion,omitempty"`
	Links ManagerLinks `json:"Links,omitempty"`
	PowerState PowerState `json:"PowerState,omitempty"`
	VirtualMedia IdRef `json:"VirtualMedia,omitempty"`
}
