/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
type ConnectedVia string

// List of ConnectedVia
const (
	CONNECTEDVIA_NOT_CONNECTED ConnectedVia = "NotConnected"
	CONNECTEDVIA_URI ConnectedVia = "URI"
	CONNECTEDVIA_APPLET ConnectedVia = "Applet"
	CONNECTEDVIA_OEM ConnectedVia = "Oem"
)