/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// A reference to a resource.
type IdRef struct {
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id,omitempty"`
}
