/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// VirtualMedia Redfish virtual media resource for manager.
type VirtualMedia struct {
	// The name of the resource.
	Id string `json:"Id,omitempty"`
	// The name of the resource.
	Name string `json:"Name"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// redfish copyright
	RedfishCopyright string `json:"@Redfish.Copyright,omitempty"`
	// description
	Description *string `json:"Description,omitempty"`
	Image *string `json:"Image,omitempty"`
	ImageName *string `json:"ImageName,omitempty"`
	Inserted *bool `json:"Inserted,omitempty"`
	ConnectedVia ConnectedVia `json:"ConnectedVia,omitempty"`
	MediaTypes []string `json:"MediaTypes,omitempty"`
	WriteProtected *bool `json:"WriteProtected,omitempty"`
	UserName *string `json:"UserName,omitempty"`
	Password *string `json:"Password,omitempty"`
	TransferMethod TransferMethod `json:"TransferMethod,omitempty"`
	TransferProtocolType TransferProtocolType `json:"TransferProtocolType,omitempty"`
	Actions VirtualMediaActions `json:"Actions,omitempty"`
}
