/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// IndicatorLed the model 'IndicatorLed'
type IndicatorLed string

// List of IndicatorLED
const (
	INDICATORLED_UNKNOWN IndicatorLed = "Unknown"
	INDICATORLED_LIT IndicatorLed = "Lit"
	INDICATORLED_BLINKING IndicatorLed = "Blinking"
	INDICATORLED_OFF IndicatorLed = "Off"
)
