/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
type TransferProtocolType string

// List of TransferProtocolType
const (
	CIFS TransferProtocolType = "CIFS"
	FTP TransferProtocolType = "FTP"
	SFTP TransferProtocolType = "SFTP"
	HTTP TransferProtocolType = "HTTP"
	HTTPS TransferProtocolType = "HTTPS"
	NFS TransferProtocolType = "NFS"
	SCP TransferProtocolType = "SCP"
	TFTP TransferProtocolType = "TFTP"
)