/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type Boot struct {
	BootSourceOverrideEnabled BootSourceOverrideEnabled `json:"BootSourceOverrideEnabled,omitempty"`
	BootSourceOverrideTarget BootSource `json:"BootSourceOverrideTarget,omitempty"`
	BootSourceOverrideTargetRedfishAllowableValues []BootSource `json:"BootSourceOverrideTarget@Redfish.AllowableValues,omitempty"`
}
