/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
type ConnectedVia string

// List of ConnectedVia
const (
	NOT_CONNECTED ConnectedVia = "NotConnected"
	URI ConnectedVia = "URI"
	APPLET ConnectedVia = "Applet"
	OEM ConnectedVia = "Oem"
)