/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// BootSourceOverrideEnabled the model 'BootSourceOverrideEnabled'
type BootSourceOverrideEnabled string

// List of BootSourceOverrideEnabled
const (
	BOOTSOURCEOVERRIDEENABLED_ONCE BootSourceOverrideEnabled = "Once"
	BOOTSOURCEOVERRIDEENABLED_CONTINUOUS BootSourceOverrideEnabled = "Continuous"
)
