/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
type TransferProtocolType string

// List of TransferProtocolType
const (
	TRANSFERPROTOCOLTYPE_CIFS TransferProtocolType = "CIFS"
	TRANSFERPROTOCOLTYPE_FTP TransferProtocolType = "FTP"
	TRANSFERPROTOCOLTYPE_SFTP TransferProtocolType = "SFTP"
	TRANSFERPROTOCOLTYPE_HTTP TransferProtocolType = "HTTP"
	TRANSFERPROTOCOLTYPE_HTTPS TransferProtocolType = "HTTPS"
	TRANSFERPROTOCOLTYPE_NFS TransferProtocolType = "NFS"
	TRANSFERPROTOCOLTYPE_SCP TransferProtocolType = "SCP"
	TRANSFERPROTOCOLTYPE_TFTP TransferProtocolType = "TFTP"
)