/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// PowerState the model 'PowerState'
type PowerState string

// List of PowerState
const (
	POWERSTATE_TRUE PowerState = "true"
	POWERSTATE_FALSE PowerState = "false"
	POWERSTATE_POWERING_ON PowerState = "PoweringOn"
	POWERSTATE_POWERING_OFF PowerState = "PoweringOff"
)
