/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ComputerSystemActions struct {
	ComputerSystemReset ComputerSystemReset `json:"#ComputerSystem.Reset,omitempty"`
}
